name: Deploy Nitric App to AWS

on:
  push:
    branches: [master] # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Pulumi CLI
        run: |
          curl -fsSL https://get.pulumi.com | sh
          echo "$HOME/.pulumi/bin" >> $GITHUB_PATH

      - name: Install Nitric CLI
        shell: bash
        run: |
          echo "Downloading Nitric install script..."
          curl -sSL https://nitric.io/install.sh -o install-nitric.sh

          echo "Running installer..."
          bash install-nitric.sh

          echo "$HOME/.nitric/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy with Nitric
        run: nitric up --stack dev --non-interactive
