name: Deploy Nitric App to AWS

on:
  push:
    branches: [master] # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Pulumi CLI
        run: |
          curl -fsSL https://get.pulumi.com | sh
          echo "$HOME/.pulumi/bin" >> $GITHUB_PATH

      - name: Install Nitric CLI (Robust)
        run: |
          mkdir -p "$HOME/.nitric/bin"

          NITRIC_VERSION="1.27.2"
          NITRIC_ARCHIVE="aws_linux_x86_64.tar.gz"
          NITRIC_URL="https://github.com/nitrictech/nitric/releases/download/v${NITRIC_VERSION}/${NITRIC_ARCHIVE}"

          echo "Downloading Nitric CLI from $NITRIC_URL..."
          curl -L "$NITRIC_URL" -o nitric-cli.tar.gz

          TEMP_EXTRACT_DIR=$(mktemp -d)
          echo "Extracting to $TEMP_EXTRACT_DIR"
          tar -xzf nitric-cli.tar.gz -C "$TEMP_EXTRACT_DIR"

          NITRIC_BIN_PATH=$(find "$TEMP_EXTRACT_DIR" -type f -name "nitric" -executable -print -quit)

          if [ -z "$NITRIC_BIN_PATH" ]; then
              echo " 'nitric' binary not found!"
              ls -R "$TEMP_EXTRACT_DIR"
              exit 1
          fi

          echo " Found nitric at $NITRIC_BIN_PATH"
          mv "$NITRIC_BIN_PATH" "$HOME/.nitric/bin/"
          rm -rf "$TEMP_EXTRACT_DIR"

          echo "$HOME/.nitric/bin" >> $GITHUB_PATH
          export PATH="$PATH:$HOME/.nitric/bin"

          echo "Adding to GitHub Actions PATH for future steps..."

          echo "$HOME/.nitric/bin" >> $GITHUB_PATH
          echo "Verifying installation..."
          ls -l $HOME/.nitric/bin
          which nitric || echo "nitric not found in path"
          nitric --version || echo "nitric command failed"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy with Nitric
        run: nitric up --stack dev --non-interactive
